# Generated by Django 4.1.3 on 2022-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0002_ads_delete_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
